# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: create output
      #  run: |          
      #    sudo mkdir output,
      #    sudo cp -r . /output

      # Runs a set of commands using the runners shell
     # - name: Run a multi-line script
     #   run: |
     #     echo Add other actions to build,
     #     echo test, and deploy your project
      - name: Push directory to another repository
        # You may pin to the exact commit or the version.
        # uses: cpina/github-action-push-to-another-repository@637125d2256c6612875516875c0e715afb799614
        uses: cpina/github-action-push-to-another-repository@v1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          # Source directory from the origin directory
          source-directory: .
          # Name of the destination username/organization
          destination-github-username: "thecyberalliance"
          # Destination repository
          destination-repository-name: "thecyberalliance.github.io"
          # Email for the git commit
          user-email: "tca_sitaics@gmail.com"
